### PR TITLE
Update Setup file for creating an instance

### PR DESCRIPTION
**Pull request by doodybrains**
We created a more detailed file according to our experiences setting up our own instances. We tried to address all of the possible issues that might arise when running commands in the terminal in order to make it beginner friendly.

@dphiffer Feel free to make changes here!

### CODE REVIEW

**Comment by dphiffer** [comment]
This looks great, @doodybrains! Could you switch this to be against the `develop` branch? It could probably just replace the `server-setup.md` file in here: https://github.com/organizer-network/organizer.network/tree/develop/docs/running

**Comment by dphiffer** [comment]
another thing is that you might find that it's easier to clone the main git URL if you don't want the extra step of keeping your fork up to date with upstream.

**Comment by doodybrains** [comment]
@dphiffer great! I think I'll stay on the fork for now (will open a new PR on develop branch) so that I can practice forking~fetching upstream~opening PRs etc. If you have any workflow advice on that process let me know. Hadar is going to follow these new instructions before meeting on Tuesday so we might have a few more things to add depending on whether or not she runs into issues on her machine.

**Comment by dphiffer** [comment]
Sounds good, yeah maybe it can be instructive to work off of a fork. I sometimes juggle multiple remotes on a repo and I think it's just a matter of remembering to `git fetch` on a regular basis. These articles might be useful to look at:

https://help.github.com/articles/configuring-a-remote-for-a-fork/
https://help.github.com/articles/syncing-a-fork/

**Pull request closed without merging**
